"""Bundled facet snapshot, used only when the live lookup fails (03 §1.2).

``fallback_catalog.json`` is regenerated by ``scripts/refresh_fallback_catalog.py``.
It is a snapshot: display names and even the set of offered values do change
(01 §4.4-4.5), so the runtime always tries ``facets:suggest`` first and warns whenever
it falls back to these values.
"""

from __future__ import annotations

import functools
import json
import pathlib
from typing import Any

__all__ = ["CATALOG_PATH", "fallback_sections", "fallback_value_map", "load_fallback_catalog"]

CATALOG_PATH = pathlib.Path(__file__).with_name("fallback_catalog.json")


@functools.lru_cache(maxsize=1)
def load_fallback_catalog() -> dict[str, Any]:
    """Parse the bundled snapshot. A missing or broken file yields an empty catalogue."""
    try:
        payload = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {"sections": [], "attribute_values": {}, "size_groups": {}}
    return payload if isinstance(payload, dict) else {}


@functools.lru_cache(maxsize=1)
def fallback_value_map() -> dict[str, dict[str, str]]:
    """``section or size-group UUID → {display name: value UUID}``.

    Size groups are keyed by their own value UUID so the resolver can look up leaves
    with the same call shape it uses for sections.
    """
    catalog = load_fallback_catalog()
    values: dict[str, dict[str, str]] = {}
    for section, mapping in (catalog.get("attribute_values") or {}).items():
        if isinstance(mapping, dict):
            values[section] = {str(k): str(v) for k, v in mapping.items()}
    for group_value, group in (catalog.get("size_groups") or {}).items():
        mapping = (group or {}).get("values")
        if isinstance(mapping, dict):
            values[group_value] = {str(k): str(v) for k, v in mapping.items()}
    return values


def fallback_sections() -> list[dict[str, Any]]:
    sections = load_fallback_catalog().get("sections")
    return list(sections) if isinstance(sections, list) else []
